parameters:
    sylius.form.type.channel.validation_groups: [monsieurbiz_nocommerce]
    monsieurbiz_sylius_nocommerce.disable_firewall.ignored_routes: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusNoCommercePlugin\:
        resource: '../../'

    MonsieurBiz\SyliusNoCommercePlugin\Form\Extension\:
        resource: '../../Form/Extension'
        tags:
            - { name: form.type_extension, priority: -10000 }

    MonsieurBiz\SyliusNoCommercePlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, priority: -10000 }

    MonsieurBiz\SyliusNoCommercePlugin\Menu\AdminCustomerShowMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.customer.show, priority: -10000 }

    MonsieurBiz\SyliusNoCommercePlugin\Menu\ShopAccountMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.shop.account, priority: -10000 }

    MonsieurBiz\SyliusNoCommercePlugin\EventListener\DisableFirewallListener:
        arguments:
            $ignoredRoutes: '%monsieurbiz_sylius_nocommerce.disable_firewall.ignored_routes%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -10000 }

    MonsieurBiz\SyliusNoCommercePlugin\Model\Config:
        arguments:
            - '%monsieurbiz_sylius_nocommerce.config%'

    Symfony\Bundle\SecurityBundle\Security\FirewallMap: '@security.firewall.map'

    monsieurbiz.nocommerce.firewall.registry: '@MonsieurBiz\SyliusNoCommercePlugin\Firewall\Registry'

    MonsieurBiz\SyliusNoCommercePlugin\Collector\NoCommerceSyliusCollector:
        autowire: false
        arguments:
            - '@sylius.context.shopper'
            - '%kernel.bundles%'
            - '%locale%'
            - '@monsieurbiz.no_commerce.provider.features_provider'
        tags:
            - { name: data_collector, template: '@SyliusCore/Collector/sylius.html.twig', id: sylius_core, priority: -512 }

    MonsieurBiz\SyliusNoCommercePlugin\Context\NoCurrencyContext:
        decorates: sylius.context.currency.channel_aware
        arguments:
            - '@MonsieurBiz\SyliusNoCommercePlugin\Context\NoCurrencyContext.inner'
            - '@monsieurbiz.no_commerce.provider.features_provider'

    MonsieurBiz\SyliusNoCommercePlugin\Registry\TemplateBlockRegistryDecorator:
        decorates: 'Sylius\Bundle\UiBundle\Registry\TemplateBlockRegistryInterface'
        arguments:
            $templateBlockRegistry: '@MonsieurBiz\SyliusNoCommercePlugin\Registry\TemplateBlockRegistryDecorator.inner'
            $featuresProvider: '@monsieurbiz.no_commerce.provider.features_provider'

    monsieurbiz.no_commerce.provider.features_provider:
        class: 'MonsieurBiz\SyliusNoCommercePlugin\Provider\FeaturesProvider'
        public: true

    # Routing Context
    MonsieurBiz\SyliusNoCommercePlugin\Routing\NoCommerceRequestContext:
        decorates: router.request_context
        arguments:
            - '@MonsieurBiz\SyliusNoCommercePlugin\Routing\NoCommerceRequestContext.inner'
            - '@monsieurbiz.no_commerce.provider.features_provider'
